server:
  port: 8081
  context-path: /
mybatis:
  typeAliasesPackage: com.distribution.common.mapper
  mapperLocations: classpath:mapper/*.xml
jdbc:
  driverClassName : com.mysql.jdbc.Driver
  url : jdbc:mysql://localhost:3306/distribution
  username : root
  password : 123456
mybatis:mapper-locations: classpath*:mapper/*.xml
mybatis:typeAliasesPackage:  com.distribution.common.mapper



