spring:
  profiles:
    active: dev
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
  resources:
    chain:
      strategy:
        content:
          enabled: false
          paths: /**

#logging:
 # config: classpath:logback.xml
  #path: "C:\\log"




