spring:
  profiles:
    active: dev
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
  resources:
    chain:
      strategy:
        content:
          enabled: false
          paths: /**
server:
  port: 8080

logging:
  config: classpath:logback.xml
  path: "/plug.log"
  level: debug
dist:
  server:
    prefix: http://localhost/


